version: '3.7'
services:
  database:
    image: postgres:12.2
    container_name: database
    ports:
      - 5432:5432
    volumes:
      - ./pg_date:/var/lib/postgresql/data
    environment: 
      HOSTNAME: "${DB_HOST}"
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: "${DB_USER}"
      PGDATA: /var/lib/postgresql/data
    restart: always
  app:
    build: ./
    container_name: cool-web-app
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      # - ./node_modules:/usr/src/app/node_modules
    ports:
      - 8080:8080
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - database
    command: "npm run start:dev"
    # command: /bin/bash -c "/usr/wait-for-it.sh --timeout=0 database:5432 -- npm run start:dev"
  nginx:
    image: nginx:1.17.9
    container_name: nginx
    volumes:
      - ./Docker/nginx.conf:/etc/nginx/conf.d/nginx.conf
    ports:
      - 8989:8989
    depends_on:
      - app